### ISSUE TITLE
Create / Review Data Schema

### ISSUE THREAD

**Issue by TheNirmata** [keelworks/LMS#56]
# Task Template

Please look into creating data schema for instructors/ students / admins. 

----

### Acceptance Criteria

- [ ] Consider referring to the systems design [here](https://www.figma.com/board/YQPyBzFHVI4cOEWWv2Rhvy/LMS-DESIGN?node-id=2-206&t=96WQVG85SH32OtKC-0l). 
- [ ] Consider how to store these objects in the database. 
- [ ] Implement access to certain views with respect to the role of the user. 
- [ ] API endpoints needs to be created with respect to the required features (refer to the Webapp system design).

### Requirement Documents 

Add sketch / API documents.
